### ISSUE TITLE
vmq docker mongodb not apply acl

### ISSUE THREAD

**Issue by molotsnk** [vernemq/vernemq#1056]
### Environment

- VerneMQ Version: 1.6.2
- OS: docker on ubuntu 16 lts
- VerneMQ configuration (part of docker-compose file)
```yml
vmq:
    image: erlio/docker-vernemq:1.6.2
    hostname: vmq
    environment:

      - "DOCKER_VERNEMQ.plugins.vmq_passwd = off"
      - "DOCKER_VERNEMQ.plugins.vmq_acl = on"
      - "DOCKER_VERNEMQ.plugins.vmq_diversity = on"
      - "DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.port = 27017"
      - "DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.host = mongos.service.consul"
      - "DOCKER_VERNEMQ_VMQ_DIVERSITY.auth_mongodb.enabled = on"
    #  - "DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.login = user"
    #  - "DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.password = pass"
      - "DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.database = mobile"
      - "DOCKER_VERNEMQ_LISTENER.ws.1 = 0.0.0.0:8000"
    #  - "DOCKER_VERNEMQ_DISCOVERY_NODE= vmq-1883.service.consul"
      - "SERVICE_NAME=vmq"
      - "SERVICE_8000_CHECK_TCP=true"
      - "SERVICE_8000_CHECK_INTERVAL=15s"
      - "SERVICE_8000_CHECK_TIMEOUT=3s"
      - "SERVICE_8000_CHECK_DEREGISTER_AFTER=20s"
```

### Expected behavior
```json
{
    "_id" : ObjectId("5c488f3821f651001ed77368"),
    "publish_acl" : [ 
        {
            "pattern" : "mv1/5c488f3821f651001ed77366/#"
        }
    ],
    "subscribe_acl" : [ 
        {
            "pattern" : "mv1/5c488f3821f651001ed77366/#"
        }
    ],
    "mountpoint" : "",
    "client_id" : "154825912815616",
    "passhash" : "$2a$10$rbiQNp77Nux1dY1RJirPoeh3.SEAmfSkH5Vjppo1/rtm5piWEfjf6",
    "username" : "5c488f3821f651001ed77366",
    "__v" : 0
}
```
I want isolate users, but it's not works.

### Actual behaviour
It's ok connected to topic, but if subscribe to "#" topic, client recieved messages from all other clients. Any ideas?
