### ISSUE TITLE
Error while scraping metrics using Prometheus

### ISSUE THREAD

**Issue by deepaksood619** [vernemq/vernemq#1237]
### Environment

- VerneMQ Version: 1.8.0
- OS: erlio/docker-vernemq:1.8.0-alpine
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: standalone (1 node)

### Expected behavior
Error should not come, metrics are exported and can be found in prometheus and vernemq:8888/metrics endpoint too, but error log is constantly coming at 10 second interval while the scrape_interval is set to 30 sec in prometheus

### Actual behaviour
`cant_parse_connect_fixed_header` Error is coming in vernemq logs

### Logs
```bash
07:56:36.405 [debug] [tcp] parse error '{cant_parse_connect_fixed_header,<<"GET /metrics HTTP/1.1\r\nHost: mqtt.vernemq.svc:1883\r\nUser-Agent: Prometheus/\r\nAccept: application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3,*/*;q=0.1\r\nAuthorization: Basic Og==\r\nX-Prometheus-Scrape-Timeout-Seconds: 10.000000\r\nAccept-Encoding: gzip\r\nConnection: close\r\n\r\n">>}' for data: <<"GET /metrics HTTP/1.1\r\nHost: mqtt.vernemq.svc:1883\r\nUser-Agent: Prometheus/\r\nAccept: application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3,*/*;q=0.1\r\nAuthorization: Basic Og==\r\nX-Prometheus-Scrape-Timeout-Seconds: 10.000000\r\nAccept-Encoding: gzip\r\nConnection: close\r\n\r\n">> and  parser state: <<>>
07:56:36.405 [warning] session stopped abnormally due to '{cant_parse_connect_fixed_header,<<"GET /metrics HTTP/1.1\r\nHost: mqtt.vernemq.svc:1883\r\nUser-Agent: Prometheus/\r\nAccept: application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3,*/*;q=0.1\r\nAuthorization: Basic Og==\r\nX-Prometheus-Scrape-Timeout-Seconds: 10.000000\r\nAccept-Encoding: gzip\r\nConnection: close\r\n\r\n">>}'
```

**Comment by ioolkos** [comment]
@deepaksood619 thanks.
This must be some other process (outside or within Prometheus) that is trying to do a HTTP request on the MQTT port (1883). Can you find out what this process is?

**Comment by deepaksood619** [comment]
@ioolkos Thanks for the reply.

I am not able to find any process that is doing http at /metrics endpoint other then prometheus. Since this is in a kubernetes network and prometheus is directly scraping pod at 8888 port and that also correctly. I double checked the config of the prometheus.

Is there any way i can debug this?

Meanwhile i will keep looking for any service that can do a HTTP GET at port 1883, but i don't think there is since there are not a lot of services in this cluster.

**Comment by dergraf** [comment]
This is likely a miss configuration of the Kubernetes Service. Please provide us the Kubernetes Service description. It should look similar to https://github.com/vernemq/vmq-operator/blob/master/examples/only_vernemq/vernemq-service.yaml

Closing as this isn't a VerneMQ issue.

**Comment by deen13** [comment]
We experience the same problem which holds us back from monitoring the vmq uptime. 

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vernemq
  namespace: xxx
  annotations:
    secret.reloader.stakater.com/reload: "xxx-secret"
  labels:
    app: vernemq
spec:
  serviceName: vernemq
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: vernemq
  template:
    metadata:
      labels:
        app: vernemq
    spec:
      serviceAccountName: vernemq
      terminationGracePeriodSeconds: 240
      containers:
        - name: vernemq
          image: xxx/vernemq
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 8883
              name: mqtts
            - containerPort: 4369
              name: epmd
            - containerPort: 44053
              name: vmq
            - containerPort: 8080
              name: ws
            - containerPort: 8443
              name: wss
            - containerPort: 8888
              name: prometheus
            - containerPort: 9100
            - containerPort: 9101
            - containerPort: 9102
            - containerPort: 9103
            - containerPort: 9104
            - containerPort: 9105
            - containerPort: 9106
            - containerPort: 9107
            - containerPort: 9108
            - containerPort: 9109
          env:
            - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
              value: "-1"
            - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
              value: "-1"
            - name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
              value: "0"
            - name: DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS
              value: "3,4,5"
            - name: DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD
              value: "off"
            - name: DOCKER_VERNEMQ_PLUGINS__VMQ_ACL
              value: "off"
            - name: DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY
              value: "on"
            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED
              value: "on"
            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD
              value: "crypt"
            - name: WEBHOOKS_CUSTOM_ENABLED
              value: "on"
            - name: WEBHOOKS_ENDPOINT
              value: "http://localhost:8101"
            - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
              value: "1"
            - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR
              value: "app=vernemq"
            - name: DOCKER_VERNEMQ_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUTH_CUSTOM_ENABLED
              value: "on"
            - name: AUTH_CUSTOM_USERNAME
              value: "cloud"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
          livenessProbe:
            httpGet:
              path: /health
              port: 8888
          readinessProbe:
            httpGet:
              path: /health
              port: 8888
          startupProbe:
            httpGet:
              path: /health
              port: 8888
            failureThreshold: 60
            periodSeconds: 3
          volumeMounts:
            - mountPath: /var/lib/vernemq
              readOnly: false
              name: data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "750m"
        - name: vmq-proxy
          image: xxx/vmq-proxy
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /usr/src/app/config/production.json
              subPath: vmq-proxy-config.json
          readinessProbe:
            httpGet:
              path: /health
              port: 8101
          livenessProbe:
            httpGet:
              path: /health
              port: 8101
          resources:
            requests:
              memory: "24Mi"
              cpu: "10m"
            limits:
              memory: "48Mi"
              cpu: "50m"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - vernemq
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          configMap:
            name: vmq-proxy-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vernemq
  namespace: xxx
  labels:
    app: vernemq
spec:
  clusterIP: None
  selector:
    app: vernemq
  ports:
    - port: 4369
      name: empd
---
apiVersion: v1
kind: Service
metadata:
  name: vernemq-prometheus
  namespace: xxx
  labels:
    app: vernemq-prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scrape-port: "8888"
spec:
  clusterIP: None
  selector:
    app: vernemq
  ports:
    - port: 8888
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: vernemq-mqtt
  namespace: xxx
  labels:
    app: vernemq-mqtt
spec:
  type: NodePort
  selector:
    app: vernemq
  ports:
    - port: 1883
      name: mqtt
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vernemq
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vernemq
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vernemq
  namespace: xxx
  labels:
    app: vernemq
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-reader
  namespace: xxx
  labels:
    app: vernemq
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-reader
  namespace: xxx
  labels:
    app: vernemq
subjects:
  - kind: ServiceAccount
    name: vernemq
    namespace: xxx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader
```
