### ISSUE TITLE
Unable to configure SSL 

### ISSUE THREAD

**Issue by joshfoeh** [vernemq/vernemq#1258]
### Environment

- VerneMQ Version: Latest Docker image 
- OS: MacOS Mojave: 10.14.1
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: standalone

### Related Issues
I have scoured the issues and found many related issues (for example, #1138 and #856 ), but none of the solutions listed there have fixed my issue. 

### Expected behavior
I am running the official VerneMQ docker image with the following docker compose file:
```
version: '2'
services:
  vernemq:
    image: erlio/docker-vernemq
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8081:8081"
      - "8883:8883"
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: on
      DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT: 127.0.0.1:8081
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: SSL_DEFAULT=127.0.0.1:8883
      DOCKER_VERNEMQ_LISTENER__WSS__REQUIRE_CERTIFICATE: on
      DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE: on
      DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT__CAFILE: /etc/ssl/ca_certificate.pem
      DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT__CERTFILE: /etc/ssl/server_certificate.pem
      DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT__KEYFILE: /etc/ssl/server_key.pem
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__CAFILE: /etc/ssl/ca_certificate.pem
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__CERTFILE: /etc/ssl/server_certificate.pem
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__KEYFILE: /etc/ssl/server_key.pem
      DOCKER_VERNEMQ_LISTENER__WSS__CAFILE: /etc/ssl/ca_certificate.pem
      DOCKER_VERNEMQ_LISTENER__WSS__CERTFILE: /etc/ssl/server_certificate.pem
      DOCKER_VERNEMQ_LISTENER__WSS__KEYFILE: /etc/ssl/server_key.pem
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: /etc/ssl/ca_certificate.pem
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: /etc/ssl/server_certificate.pem
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: /etc/ssl/server_key.pem
    volumes:
      - "/Users/XXX/security/certs/vernemq/:/etc/ssl"
```
I have tried many different combinations of the above:
- allow anonymous as both on and off
- require certificate as both on and off (for both SSL and WSS)
- only setting default files (e.g. setting DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT__CAFILE but not DOCKER_VERNEMQ_LISTENER__WSS__CAFILE), and the opposite, only setting the variable without default
- Using VerneMQ's provided test certs found [here](https://github.com/vernemq/vernemq/tree/master/apps/vmq_server/test/ssl) (all-ca.crt, server.crt, and server.key)

I have looked into the VerneMQ Docker container as it's running to look at the `vernemq.conf` file and all the variables I am setting seem to have been used.

I expect to be able to connect to an encrypted port via a client with the correct certs, but to take any other possible errors out of it I have been using the `openssl s_client` to test. I should be able to run the command `openssl s_client -connect localhost:8883` and see some information about the certs.

### Actual behaviour

When I run `openssl s_client -connect localhost:8883` I get the following:
```
CONNECTED(00000005)
4404373100:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.200.4/libressl-2.6/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1563296012
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```
I am also unable to connect with any client I have tried, clients I have written and existing clients from online, due to an `SSLHandshakeException`.

As mentioned above I have tried many different combinations of configuration variables and cert/key files, all give the same output listed above when I try and connect.
