### ISSUE TITLE
Can't use dot (.) symbol in password: received_payload_not_json

### ISSUE THREAD

**Issue by Foxcool** [vernemq/vernemq#1264]
Hi. At a minimum, the point does not accept the service in the body of the password. Is this the expected behavior?

### Environment

- VerneMQ Version: 1.8.0
- OS: erlio/docker-vernemq:1.8.0 image (on Fedora 29)

```
    mqtt_broker:
        image: erlio/docker-vernemq:1.8.0
        container_name: "jwt_mqtt_broker"
        restart: on-failure
        networks:
            - auth
        environment:
            - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=info
            - DOCKER_VERNEMQ_USER_jwt-vernemq=****
            - DOCKER_VERNEMQ_USER_test=test

            - DOCKER_VERNEMQ_PLUGINS.vmq_webhooks=on
            - DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook1.hook=auth_on_register
            - DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook1.endpoint=http://jwt-vernemq:34567/
        ports:
            - 1883:1883
            - 8690:8080
```

### Expected behavior

Transfer payload to webhook service

### Actual behaviour
- we used webhooks feature for auth by JWT token.
- JWT token have dot (.) symbol for splitting token body and signature.
- we know, that we can encode token, but maybe this is a bug?
- broker can't parse payload and transfer data to service

```
jwt_mqtt_broker | 15:10:09.121 [error] calling endpoint failed due to received_payload_not_json
jwt_mqtt_broker | 15:10:09.121 [warning] can't authenticate client {[],<<"clientId-ksRhA4Zdv5">>} from 172.18.0.1:48618 due to received_payload_not_json
```
