### ISSUE TITLE
$SYS/broker/connection/<client-id>/state always 0

### ISSUE THREAD

**Issue by caevv** [vernemq/vernemq#1306]
### Environment

- VerneMQ Version: 1.8.0-alpine
- OS: Docker
Container config:
```
additionalEnv:
  - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
    value: "on"
# https://docs.vernemq.com/configuration/bridge
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_BRIDGE
    value: "on"
  - name: DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__CAFILE
    value: "./etc/secrets/cacerts.pem"
  - name: DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__CERTFILE
    value: "./etc/secrets/cert.pem"
  - name: DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__KEYFILE
    value: "./etc/secrets/key.pem"
  - name: DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__INSECURE
    value: "off"
  - name: DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__TLS_VERSION
    value: "tlsv1.2"
  # https://docs.vernemq.com/configuration/listeners
  - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT
    value: "0.0.0.0:8883"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__ALLOWED_PROTOCOL_VERSIONS
    value: "3,4,5,131"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__CAFILE
    value: "./etc/secrets/cacerts.pem"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE
    value: "./etc/secrets/cert.pem"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE
    value: "./etc/secrets/key.pem"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE
    value: "on"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__USE_IDENTITY_AS_USERNAME
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "on"
```

Mosquitto config:
```
notifications true
bridge_protocol_version mqttv31
try_private true
```

Tried also with 
```
bridge_protocol_version mqttv311
try_private false
```
### Expected behavior

On a bridge between Mosquitto with VerneMQ the topic on VerneMQ side `$SYS/broker/connection/<client-id>/state` should be `1`. But is always `0`. This was not the case on a Mosquitto to Mosquitto bridge.

On local Mosquitto it will have `1` when online:
```
$ mosquitto_sub -h 127.0.0.1 -p 1883 -t '$SYS/broker/connection/#' -v
$SYS/broker/connection/<client-id>/state 1
```

### Actual behaviour

VerneMQ `$SYS/broker/connection/<client-id>/state` is always `0`.
