### ISSUE TITLE
allow also names (not only IPs) in configuration of 'listener.ssl.default'

### ISSUE THREAD

**Issue by MartinEnders** [vernemq/vernemq#1459]
There have already been discussions were the developers of vernemq explained why it is not possible to use 0.0.0.0 as IP for the default ssl listener which is ok. But for dynamic environments like docker deployments it would be useful to be able to use a name instead of an IP-address.

### Environment

- VerneMQ Version: 1.10.2
- OS: Docker image vernemq/vernemq (29.03.2020)
- Erlang/OTP version (if building from source): n/a
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: standalone

Docker configuration for the service 'vernemq' in my deployment:

```yaml
  vernemq:
    image: vernemq/vernemq
    restart: unless-stopped
    hostname: vernemq-docker-prod
    user: root
    ports:
      - 1883:1883
      - 8883:8883
      - 18880:8888
    volumes:
      - ../letsencrypt/:/certs:ro
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off
      - DOCKER_VERNEMQ_listener.ssl.certfile=/certs/live/SOMEDOMAIN/fullchain.pem
      - DOCKER_VERNEMQ_listener.ssl.keyfile=/certs/live/SOMEDOMAIN/privkey.pem
      - DOCKER_VERNEMQ_listener.ssl.cafile=/certs/live/SOMEDOMAIN/chain.pem
      - DOCKER_VERNEMQ_listener.ssl.default=172.19.0.7:8883
      - DOCKER_VERNEMQ_plugins.vmq_diversity=on
      - DOCKER_VERNEMQ_plugins.vmq_passwd=off
      - DOCKER_VERNEMQ_plugins.vmq_acl=off
      - DOCKER_VERNEMQ_vmq_diversity.auth_mongodb.enabled=on
      - DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.host=mongo
      - DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.port=27017
      - DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.database=vernemq_auth
    networks:
      i40net:

```

### Expected behavior

In my docker environment I can not ensure a specific IP-address for the running service so I would expect that the IP is detected automatically for SSL-MQTT (like it is already done for NON-SSL-MQTT) or that I can fill in a name (e.g. localhost, or the docker service name)

It should be possible to enter a name instead of an IP-address in the configuration e.g.:
```
      - DOCKER_VERNEMQ_listener.ssl.default=localhost:8883
```

### Actual behaviour

Currently it is only possible to enter an IP. The problem can be reproduced by adding an name instead of an IP for the ssl default listener:

```
      - DOCKER_VERNEMQ_listener.ssl.default=localhost:8883
```

Best regards
Martin
