### ISSUE TITLE
Lua on_publish hook is not called for bridged messages

### ISSUE THREAD

**Issue by michael-sayapin** [vernemq/vernemq#1497]
### Environment

- VerneMQ Version: 1.10.0
- OS: erlio/docker-vernemq:latest on Docker 19.03.8 on Ubuntu 20.04
- Cluster size/standalone: standalone
- VerneMQ configuration (vernemq.conf) or the changes from the default:

```
  vernemq_master:
    image: erlio/docker-vernemq:latest
    volumes:
      - ./vernemq/scripts:/scripts:ro
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_COMPOSE=1
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_DISTRIBUTED_COOKIE=xxx
      - DOCKER_VERNEMQ_RETRY_INTERVAL=5
      - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=debug
      - DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION=1d
      - DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES=10000
      - DOCKER_VERNEMQ_UPGRADE_OUTGOING_QOS=on
      - DOCKER_VERNEMQ_SYSTREE_INTERVAL=5000
      - DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=on
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__SCRIPT_DIR=/scripts
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST=redis_master
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PORT=6379
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PASSWORD=xxx
      - DOCKER_VERNEMQ_PLUGINS__VMQ_BRIDGE=on
      - DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0=mosquitto:1883
      - DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__CLEANSESSION=off
      - DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__CLIENT_ID=auto
      - DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__KEEPALIVE_INTERVAL=60
      - DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__RESTART_TIMEOUT=5
      - DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__TRY_PRIVATE=off
      - DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__TOPIC__1=send in 2
```

Running a following script:

```
log.info("hello from lua")

function on_deliver(pub)
    log.info("on_deliver")
end

function on_publish(pub)
    log.info("on_publish")
end

-- the hooks table specifies which hooks this plugin is implementing
hooks = {
    on_deliver = on_deliver,
    on_publish = on_publish
}
```

### Expected behavior

- clients publish to `send` topic on `mosquitto`,
- MQTT bridge imports the messages from the topic with QoS 2,
- lua `on_publish` script gets called.

### Actual behaviour

- lua `on_publish` script is not called.

### Context

We use multiple Mosquitto-based MQTT brokers at the edge to collect data from IoT devices. The plan is to sink the messages into VerneMQ cluster via `in`-based bridging, and use Lua to push messages into Redis Streams for further processing. Unfortunately I wasn't able to make Lua script for bridged messages work.
