### ISSUE TITLE
Authorize user using MYSQL

### ISSUE THREAD

**Issue by Fossil01** [vernemq/vernemq#1552]
Hi,

I am running a VerneMQ cluster in Docker with these settings:

```yaml
    environment:
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq-master
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: debug
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: 'on'
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: 'off'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'off'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__HOST: '10.100.20.11'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__PORT: '3306'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__USER: 'vernemq'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__PASSWORD: 'blablabla'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__DATABASE: 'vmqtest'
      DOCKER_VERNEMQ_VMQ_DIVERSITY.mysql.password_hash_method: 'sha256'
```

Which results in the following vernemq.conf in the container:

```
accept_eula=yes
vmq_diversity.mysql.password_hash_method=sha256
log.console.level=debug
plugins.vmq_diversity=on
vmq_diversity.mysql.port=3306
vmq_diversity.mysql.user=vernemq
vmq_diversity.mysql.database=vmqtest
vmq_diversity.mysql.password=blablabla
vmq_diversity.mysql.host=10.100.20.11
allow_anonymous=off
plugins.vmq_passwd=off
plugins.vmq_acl=off
log.console=console
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.0.11.2:1883
listener.ws.default = 10.0.11.2:8080
listener.vmq.clustering = 10.0.11.2:44053
listener.http.metrics = 10.0.11.2:8888
########## End ##########
```

It boots up fine and the cluster is fine too. Then I added the following to my MySQL table ( I still have no clue how the hell those patterns work though):

```sql
INSERT INTO
    vmq_auth_acl (
        mountpoint,
        client_id,
        username,
        password,
        publish_acl,
        subscribe_acl
    )
VALUES
    (
        '',
        '123',
        'testuser',
        SHA2('supersecretpassword', 256),
        '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
        '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]'
    );
```

I am trying to login using MQTT Explorer on my Mac and the VMQ logs show:

```
2020-06-29T11:35:21Z New session with PID <9479.6051.0> found for client "123"
2020-06-29T11:35:21Z <9479.6051.0> MQTT RECV: CID: "123" CONNECT(c: 123, v: 4, u: testuser, p: supersecretpassword, cs: 1, ka: 60)
2020-06-29T11:35:21Z <9479.6051.0> Trace session for 123 stopped
```

The client says: `Not authorized.`

Any idea?
