### ISSUE TITLE
Limit cipher suites in Erlang SSL

### ISSUE THREAD

**Issue by kdaveid** [vernemq/vernemq#1594]
We are using ECC certificates based on `prime256v1` curve for TLS 1.2 connections. We would like to limit the cipher suites on Vernemq to a predefined group or (better) to exclude some weak suites via configuration. 

For instance, exclude these weak cihper suites:  `secp160k1`, `secp160r1`, `secp160r2`, `secp192k1`, `prime192v1`.

As you're using Erlang SLL we consulted the [docs](https://erlang.org/doc/apps/ssl/ssl.pdf) and found out that we could attach to Erlang shell and probably could run something like: 
```
 Suites =
 ssl:filter_cipher_suites(Default,
 [
  {key_exchange, fun(ecdh_ecdsa) -> true; (_) -> false end},  
  {cipher, fun(secp160k1) ->false; (_) ->false end},
  {cipher, fun(secp160r1) ->false; (_) ->false end},
  {cipher, fun(secp160r2) ->false; (_) ->false end},
  {cipher, fun(secp192k1) ->false; (_) ->false end},
  {cipher, fun(prime192v1) ->false; (_) ->false end}
]).

// and some setting, code...?
```

But we would rather have this via configuration.

How can we achieve this?

### Environment
- VerneMQ Version: vernemq/vernemq:1.10.2-1-alpine
- OS: Ubuntu / Docker version 19.03.12,
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: Standalone

**Comment by ioolkos** [comment]
@kdaveid  Thanks... here are the supported ciphers listed in the `vmq_ssl` module:
https://github.com/vernemq/vernemq/blob/43b186bd61ab9bc77f3d5ca7aa1f4bb43885206e/apps/vmq_server/src/vmq_ssl.erl#L147

You can add the ciphers to the `vernem.conf` with a key of `listener.ssl.$name.ciphers` with $name being the name of your TLS listener. 
You can add the ciphers based on the list in the code above. I think you need to separate them with a ":", but I might have forgotten the format. Let me know if you have any troubles configuring this.

**Comment by kdaveid** [comment]
According to your hint we updated our `docker-compose.yml` to the following (extract):

```
  mqtt-server:
    image: vernemq/vernemq:1.10.2-1-alpine
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0: 0.0.0.0:8883
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0__CAFILE: /cacerts.pem
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0__CERTFILE: /servercert.pem
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0__CIPHERS: ECDH-ECDSA-AES128-GCM-SHA256:ECDH-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0__DEPTH: 2
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0__KEYFILE: /serverkey.pem
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0__REQUIRE_CERTIFICATE: "on"
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0__TLS_VERSION: tlsv1.2
      DOCKER_VERNEMQ_LISTENER__SSL__LISTENER0__USE_IDENTITY_AS_USERNAME: "on"
   ...
``` 

And verified:
```
7773/tcp open  unknown
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|     compressors:
|       NULL
|     cipher preference: client
|_  least strength: A
``` 

This works like a charm 🎉
Thank you! 🙏🏼
