### ISSUE TITLE
Invalid protocol version 5

### ISSUE THREAD

**Issue by bpoulse** [vernemq/vernemq#1616]
Bear with me on this one, there are several interacting pieces of software, so if this is the wrong repo to post this issue in please let me know.

I have setup a Vernemq cluster (1.10.3) using the Helm chart (1.6.3) in a Kubernetes (microk8s 1.18) deployment. The Helm values.yaml is as below:
```
additionalEnv:
  - name: DOCKER_VERNEMQ_ACCEPT_EULA
    value: "yes"
  - name: DOCKER_VERNEMQ_USER_test
    value: "123456"
service:
  ws:
    enabled: true
```
I am communicating with this cluster using an MQTT.js WebSocket client. When connecting to the broker, specifying protocol version 4 or less results in no issues, publish and subscribing works as anticipated:
```
client = mqtt.connect(__MQTT_URL__, {
  username: 'test',
  password: '123456',
  protocolVersion: 4,
});
```
However, when using `protocolVersion: 5` I get the following warning in the vernemq cluster:
`17:43:24.975 [warning] invalid protocol version for {[],undefined} 5`
And the client times out. Is this an error? My understanding was that Vernemq supported MQTT 5.0. Is MQTT.js potentially sending a malformed packet?
