### ISSUE TITLE
PubSub accross cluster using helm/k8s not working after scale-down than scale-up

### ISSUE THREAD

**Issue by michaelyaakoby** [vernemq/vernemq#1659]
### Environment

- VerneMQ Version: 1.11.0
- OS: alpine
- Deployed on k8s using helm: `helm install vernemq vernemq/vernemq -f values.yaml`
- VerneMQ configuration, `values.yaml`:
```yaml
replicaCount: 2
service:
  type: LoadBalancer
  loadBalancerIP: ...............
additionalEnv:
  - name: DOCKER_VERNEMQ_ACCEPT_EULA
    value: "yes"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "on"
  - name: DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS
    value: "3,4,5"
```
- Client: Eclipse Paho (`org.eclipse.paho.mqttv5.client`, version `1.2.5`) using the async API

### Expected behaviour
- I'm running a test where multiple publishers and multiple subscribers are connecting to the cluster using the load-balancer
- when I scale down to 1 pod than back to 2 pods than restart my test, many of the published messages aren't delivered to the subscribers

### Actual behaviour
 - I suspect that if the publisher is connected to a different pod than the one used by the subscriber, the message isn't sent across the cluster 
- Its a bit similar to #586

Anyways, I assume its a configuration I miss (maybe persistent volume?), however *kudos for the great helm chart - very nice!*
