### ISSUE TITLE
Issue with Authentication and Authorization with mysql

### ISSUE THREAD

**Issue by westforkfab** [vernemq/vernemq#1665]
### Environment

- VerneMQ Version: release,"vernemq","1.10.4.1","10.7"
- OS: Linux (Linux e1554ba7b619 5.8.14-200.fc32.x86_64 #1 SMP Wed Oct 7 14:47:56 UTC 2020 x86_64 GNU/Linux)
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default

```
########## Start ##########
accept_eula=yes
log.console.level=debug
listener.ssl.default=0.0.0.0:8884
plugins.vmq_passwd=off
plugins.vmq_diversity=on
vmq_diversity.mysql.port=3306
vmq_diversity.mysql.user=mqttuser
listener.ssl.keyfile=/vernemq/etc/certs/server.key
vmq_diversity.auth_mysql.enabled=on
listener.ssl.certfile=/vernemq/etc/certs/server.crt
vmq_diversity.mysql.database=***********
vmq_diversity.mysql.password=***********
vmq_diversity.mysql.host=172.16.1.15
vmq_diversity.mysql.password_hash_method=sha256
log.console.file=/vernemq/log/broker.log
allow_anonymous=off
listener.ssl.cafile=/vernemq/etc/certs/ca.crt
plugins.vmq_acl=off
log.console=file
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 172.16.1.11:1883
listener.ws.default = 172.16.1.11:8080
listener.vmq.clustering = 172.16.1.11:44053
listener.http.metrics = 172.16.1.11:8888
########## End ##########
```

- Cluster via haproxy (2 nodes) using Docker
Form docker-compose.yml
```
    image: vernemq/vernemq
    restart: always
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_DISCOVERY_NODE: '172.16.1.11'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: 'on'
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: 'off'
      DOCKER_VERNEMQ_PLUGINS__vmq_passwd: 'off'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__auth_mysql.enabled: 'on'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__HOST: '172.16.1.15'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__PORT: '3306'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__USER: 'mqttuser'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__PASSWORD: '************************'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__DATABASE: 'mqtt_test'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__PASSWORD_HASH_METHOD: 'sha256'
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: '/vernemq/etc/certs/ca.crt'
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: '/vernemq/etc/certs/server.crt'
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: '/vernemq/etc/certs/server.key'
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: '0.0.0.0:8884'
      DOCKER_VERNEMQ_LOG__CONSOLE: 'file'
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: 'debug'
      DOCKER_VERNEMQ_LOG__CONSOLE__FILE: '/vernemq/log/broker.log'

```

### Expected behaviour
The broker should authenticate and authorize the "right" clients checking credentials and authorizations from mysql

### Actual behaviour
The clients can subscribe and publishing, but the subscriber does not get the messages.
Basically, using mosquitto_sub, I am able to connect to the broker:

```
mosquitto_sub -h localhost -p 8883 -u ENGINE -P 21228068524ba360ff232ca96aab316cd99731e7324ce66ebf363bb5f77277da -d --cafile ../vernemqtt/certs/ca.crt --insecure -i ENGINE -t '#' -d -v
Client ENGINE sending CONNECT
Client ENGINE received CONNACK (0)
Client ENGINE sending SUBSCRIBE (Mid: 1, Topic: #, QoS: 0, Options: 0x00)
Client ENGINE received SUBACK
Subscribed (mid: 1): 0
Client ENGINE sending PINGREQ
Client ENGINE received PINGRESP

```
When I am publish a message, using mosquitto_pub
```
mosquitto_pub -h 192.168.103.28 -p 8883 -u ENGINE -P 21228068524ba360ff232ca96aab316cd99731e7324ce66ebf363bb5f77277da -d --cafile ../vernemqtt/certs/ca.crt --insecure -i ENGINE -t /notifications/aaa/12345 -m "hello" -d --repeat 2
Client ENGINE sending CONNECT
Client ENGINE received CONNACK (0)
Client ENGINE sending PUBLISH (d0, q0, r0, m1, '/notifications/aaa/12345', ... (5 bytes))
Client ENGINE sending PUBLISH (d0, q0, r0, m2, '/notifications/aaa/12345', ... (5 bytes))

```
The messages are not received by the subscriber.
I can't find where is the issue within the configuration if any.

Content of vmq_auth_acl table:

```
select * from vmq_auth_acl;
+------------+--------------+--------------+------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------+
| mountpoint | client_id    | username     | password                                                         | publish_acl                                                              | subscribe_acl                                                            |
+------------+--------------+--------------+------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------+
|            | ENGINE       | ENGINE       | 21228068524ba360ff232ca96aab316cd99731e7324ce66ebf363bb5f77277da | [{"pattern":"/notifications/aaa/#"},{"pattern":"/notifications/engine"}] | [{"pattern":"/notifications/aaa/#"},{"pattern":"/notifications/engine"}] |
+------------+--------------+--------------+------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

Actual mysql.lua script (`from etc/scripts/`)

```
require "auth/auth_commons"

function my_auth_on_register(reg)

    if reg.username ~= nil and reg.password ~= nil then
	sql = "SELECT publish_acl, subscribe_acl FROM vmq_auth_acl WHERE username = '"..reg.username.."' AND password = '"..reg.password.."';"
        results = mysql.execute(pool, sql)
        if #results == 1 then
            row = results[1]
            publish_acl = json.decode(row.publish_acl)
            subscribe_acl = json.decode(row.subscribe_acl)
            cache_insert(
                reg.mountpoint, 
                reg.client_id, 
                reg.username,
                publish_acl,
                subscribe_acl
                )
	    log.info("[auth_on_register] SUCCESS")
            return true
        else
	   log.info("[auth_on_register] ERROR")
            return false
        end
    end
end


function my_auth_on_publish(pub)
	log.info("[my_auth_on_publish] pub topic: "..pub.topic)
	return true
end

function my_auth_on_subscribe(sub)
	log.info("[my_auth_on_subscribe] sub topic: "..pub.topics[1])
	return true
end

pool = "auth_mysql"
config = {
    pool_id = pool
}

mysql.ensure_pool(config)
hooks = {
    auth_on_register = my_auth_on_register,
    auth_on_publish = my_auth_on_publish,
    auth_on_subscribe = my_auth_on_subscribe,
    on_unsubscribe = on_unsubscribe,
    on_client_gone = on_client_gone,
    on_client_offline = on_client_offline,
    on_session_expired = on_session_expired,

    auth_on_register_m5 = auth_on_register_m5,
    auth_on_publish_m5 = auth_on_publish_m5,
    auth_on_subscribe_m5 = auth_on_subscribe_m5,
}

```
