### ISSUE TITLE
MacOS build in conda environment: beam.smp fails to load libtinfo.6.dylib

### ISSUE THREAD

**Issue by tomasgareau** [vernemq/vernemq#1704]
### Environment

- VerneMQ Version: 1.11.0-13-gdd3ddc0
- OS: MacOS Mojave 10.14.6
- Erlang/OTP version (if building from source): Output of `cat .../erlang/releases/RELEASES`:
```bash
[{release,"Erlang/OTP","23","11.1.5",
[{kernel,"7.2","....../erlang/lib/kernel-7.2"},
{stdlib,"3.14","....../erlang/lib/stdlib-3.14"},
{sasl,"4.0.1","....../lib/erlang/lib/sasl-4.0.1"}],
permanent}].
```
          
- VerneMQ configuration (vernemq.conf) or the changes from the default: No changes from default
- Cluster size/standalone: Standalone

- Running in a conda environment:
```yaml
name: architecture-playground
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - paho-mqtt=1.5.0
  - conda-forge::erlang=23.2.1
  - conda-forge::ncurses=6.2
  - snappy
  - kubernetes-helm
  - prometheus_client
  - scipy
  - matplotlib
  - numpy
  - autograd
  - numba
```

### Expected behaviour

- git clone https://github.com/vernemq/vernemq
- make rel
- cd _build/default/rel/vernemq
- ./bin/vernemq console works

### Actual behaviour

- beam.smp fails to load the libtinfo dylib

```
dyld: Library not loaded: @rpath/libtinfo.6.dylib
  Referenced from: /<PATH_TO_VERNEMQ>/_build/default/rel/vernemq/erts-11.1.5/bin/beam.smp
  Reason: image not found
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information
```

- libtinfo.6.dylib **is** in the conda environment's /lib directory

### Workaround

- Use install_name_tool to add an rpath to the conda environment's /lib directory to beam.smp:

```bash
install_name_tool -add_rpath /<PATH_TO_CONDA_ENV>/lib/. /<PATH_TO_VERNEMQ>/_build/default/rel/vernemq/erts-11.1.5/bin/beam.smp
```

### Question/issue

I suspect that this is a conda or environment issue, not a VerneMQ issue, but I am not very familiar with rpath or the Erlang build/linking process. I'm submitting this issue primarily so that anyone else who bumps into it can find a quick workaround or in the hope that someone in the VerneMQ community is familiar enough with rpath witchcraft that they can identify a step in the build process that would allow us to correctly detect conda libs.

No problem if you'd like to close this issue as "not a VerneMQ issue"!
