### ISSUE TITLE
VerneMQ can't reconfigure http listener

### ISSUE THREAD

**Issue by Roydon** [vernemq/vernemq#1768]
I have VerneMQ single node running with following configuration 

```
            - name: DOCKER_VERNEMQ_ACCEPT_EULA
              value: "yes"
            - name: MY_POD_NAME
              value: "vernemq"
            - name: DOCKER_VERNEMQ_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DOCKER_VERNEMQ_KUBERNETES_APP_LABEL
              value: "vernemq"
            - name: DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL
              value: "debug"
            - name: DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR
              value: "app=vernemq"
            - name: DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS
              value: "3,4,5"
            - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
              value: "on"
            - name: DOCKER_VERNEMQ_KUBERNETES_INSECURE
              value: "1"
            - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
              value: "-1"
            - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
              value: "-1"
            - name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
              value: "0"
            - name: DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT
              value: "0.0.0.0:1883"
            - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT
              value: "0.0.0.0:8883"
            - name: DOCKER_VERNEMQ_LISTENER__WS__DEFAULT
              value: "0.0.0.0:8080"
            - name: DOCKER_VERNEMQ_LISTENER__HTTP__METRICS
              value: "0.0.0.0:8888"
            - name: DOCKER_VERNEMQ_LISTENER__HTTP__DEFAULT
              value: "0.0.0.0:8888"
            - name: DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE
              value: "on"
            - name: DOCKER_VERNEMQ_LISTENER__SSL__CAFILE
              value: "/vernemq/cert/ca.crt"
            - name: DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE
              value: "/vernemq/cert/server.crt"
            - name: DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE
              value: "/vernemq/cert/server.key"
            - name: DOCKER_VERNEMQ_LISTENER__SSL__CRLFILE
              value: "/tmp/shared/ca.crl"
            - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
              value: "on"
```
But when the container starts I see following int he logs 

```
22:47:44.276 [error] can't reconfigure http listener({0,0,0,0}, 8888) with Options [{max_connections,10000},{nr_of_acceptors,10},{config_mod,vmq_http_config},{config_fun,config},{proxy_protocol,false}] due to {already_started,<0.380.0>}
```
This appears just once when the container start.  everything works okay. What I am missing here ?

I am using `vernemq/vernemq:1.11.0`
