### ISSUE TITLE
Clustering not working when running in Docker using published ports

### ISSUE THREAD

**Issue by pablitovicente** [vernemq/vernemq#1779]
### Environment

- VerneMQ Version: 1.11
- OS: Docker
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default: see "Additional details and commands to reproduce" added below
- Cluster size/standalone: 2 nodes cluster

### Expected behaviour

When running Vernemq from within Docker using published ports is possible for the cluster to work correctly.

### Actual behaviour

When running Vernemq from within Docker using published ports messages published to any of the nodes only reach the node which received the message. 

### Additional details and commands to reproduce

Our objective is to be able to run different nodes of a VerneMQ (VMQ) cluster in the same LAN (local network),
running inside a Docker container each, but exposing only a (small) number of mapped ports to the host network.

In particular, the VMQ node to be used as the discovery node must be running inside a docker-compose named docker network, 
where the IP address and most of the ports inside that container are something completely different from the actual host network 
configuration. This container with the discovery node may have a number of ports mapped (published) in order to get the VMQ cluster connected, but as detailed below, this is apparently not yet working.

The other nodes in the VMQ cluster are running on different computers and may or may not be connected to the host network (network="host")  each, both are possible in this deployment, but for completeness we have written down the behavior in either case, too.

We were not able to make the cluster work properly with the desired setup; the next section describes the configurations we tried and what were the results.

#### Setup used for the attemps:

- two computers on the same network
- firewall disabled on both computers
- both running same Docker version
- VMQ always running from within Docker

#### Working fine: 

_**Both nodes using host's network (--network="host")**_

- Status page http://localhost:8888/status shows all is ok
- Messages published to either of the nodes reach all nodes
- It's possible to telnet to 1883, 4369, 8080, 8888, 9100, 44053 from both machines (both from inside the containers and outside of them)
- All ok: No errors or warnings in the logs

Commands used:
- discovery node: `docker run --network="host" -e"DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=debug" -e"DOCKER_VERNEMQ_DISTRIBUTED_COOKIE=SUP34S3CRETC00KIE" -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d vernemq/vernemq`
- joining node: `docker run --network="host" -e"DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=debug" -e"DOCKER_VERNEMQ_DISCOVERY_NODE=192.168.0.113" -e"DOCKER_VERNEMQ_DISTRIBUTED_COOKIE=SUP34S3CRETC00KIE" -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d vernemq/vernemq`

#### Not working:

_**Discovery node using published ports (-p xyz:xyz) but otherwise inside a different docker-compose network and Other joining node using host's network (--network="host")**_

- Status page http://localhost:8888/status shows all is ok
- Messages published on the discovery node are seen by both nodes
- Messages published on the joining node are seen by the joining node but are not seen on the discovery node
- It's possible to telnet to 1883, 4369, 8080, 8888, 9100, 44053 from both machines (both from inside the containers and outside of them)
- Warning in joining node:
10:23:51.531 [debug] started plumtree_metadata_manager exchange with 'VerneMQ@192.168.0.113' (<0.956.0>)
10:23:51.534 [debug] 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
10:23:51.548 [debug] completed metadata exchange with 'VerneMQ@192.168.0.113'. nothing repaired

_So this is not working fine as messages published on the joining node are not seen on the discovery node_

Commands used:

- discovery node (docker-compose.yml): 
```version: '3'
services:
  verne0:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
      DOCKER_VERNEMQ_DISTRIBUTED_COOKIE: SUP34S3CRETC00KIE
      DOCKER_VERNEMQ_NODENAME: '192.168.0.113'
    ports:
      - 1883:1883
      - 44053:44053
      - 4369:4369
      - 9100-9109:9100-9109
      - 8888:8888
```

- joining node: `docker run --network="host" -e"DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=debug" -e"DOCKER_VERNEMQ_DISCOVERY_NODE=192.168.0.113" -e"DOCKER_VERNEMQ_DISTRIBUTED_COOKIE=SUP34S3CRETC00KIE" -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d vernemq/vernemq`

_**Both nodes using published ports (-p xyz:xyz for ports 1883, 4369, 8888, 9100, 44053)**_

- Status page http://localhost:8888/status shows all is ok
- Messages published on each node only reach each node
- It's possible to telnet to 1883, 4369, 8080, 8888, 9100, 44053 from both machines (both from inside the containers and outside of them)
- Error in joining node: 
12:12:16.435 [warning] can't connect to cluster node 'VerneMQ@192.168.0.113' due to timeout
- Error on discovery: 
08:49:55.581 [warning] can't connect to cluster node 'VerneMQ@172.18.0.2' due to timeout

_So this is not working fine as messages published on any node are not seen by the other node, respectively_

Commands used:

- discovery node (docker-compose.yml):
```
version: '3'
services:
  verne0:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
      DOCKER_VERNEMQ_DISTRIBUTED_COOKIE: SUP34S3CRETC00KIE
      DOCKER_VERNEMQ_NODENAME: '192.168.0.113'
    ports:
      - 1883:1883
      - 44053:44053
      - 4369:4369
      - 9100-9109:9100-9109
      - 8888:8888
```      
- joining node (docker-compose.yaml):
```
version: '3'
services:
  verne0:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
      DOCKER_VERNEMQ_DISTRIBUTED_COOKIE: SUP34S3CRETC00KIE
      DOCKER_VERNEMQ_DISCOVERY_NODE: '192.168.0.113'
    ports:
      - 1883:1883
      - 44053:44053
      - 4369:4369
      - 9100-9109:9100-9109
      - 8888:8888
```
### extra notes

- for all three of the test scenarios all ports shown by "vmq-admin listener show" were the same the binding IP was the docker internal one 
when published ports were being used
- "vmq-admin cluster show" showed all nodes as running
- as stated above telnet from both inside and outside the containers to the relevant ports was possible

### some additional questions

- how can we debug this issue further?
- Are there any examples somewhere running a similar setup?
- Is there any known limitation for the required setup?
