### ISSUE TITLE
Use CN as Username not working over nginx proxy websockets

### ISSUE THREAD

**Issue by jadbaz** [vernemq/vernemq#1783]
### Issue
`DOCKER_VERNEMQ_LISTENER__WS__PROXY_PROTOCOL_USE_CN_AS_USERNAME` (listener.ws.proxy_protocol_use_cn_as_username) is not working. The username is not being derived from the certificate common name
- I'm connecting through [mqtt-explorer](https://github.com/thomasnordquist/MQTT-Explorer)
- I issued a certificate to "user1".
- I added it to mqtt-explorer
- My user in vernemq is undefined

### Environment
- VerneMQ Version: vernemq/vernemq:latest-alpine
- OS: Docker for Windows, WSL
- Erlang/OTP version (if building from source): 
- VerneMQ configuration (vernemq.conf) or the changes from the default: ref [github.com/jadbaz/vernemq-issue-reproducer](https://github.com/jadbaz/vernemq-issue-reproducer)
- Cluster size/standalone: 1 docker container

### Expected behaviour
```
$ docker-compose exec mqttbroker vmq-admin session show
+-----------+-----------+------------+------------+-----------+-----------+
| client_id | is_online | mountpoint | peer_host  | peer_port | user      |
+-----------+-----------+------------+------------+-----------+-----------+
| user1     | true      |            | 172.25.0.2 | 60716     | user1 |
+-----------+-----------+------------+------------+-----------+-----------+
```
### Actual behaviour
```
$ docker-compose exec mqttbroker vmq-admin session show
+-----------+-----------+------------+------------+-----------+-----------+
| client_id | is_online | mountpoint | peer_host  | peer_port | user      |
+-----------+-----------+------------+------------+-----------+-----------+
| user1     | true      |            | 172.25.0.2 | 60716     | undefined |
+-----------+-----------+------------+------------+-----------+-----------+
```

### Reproducer
Check out the reproducer: [github.com/jadbaz/vernemq-issue-reproducer](https://github.com/jadbaz/vernemq-issue-reproducer). Just `docker-compose up -d` and then use the client certs in `client-certs` directory to connect to the broker

**Comment by ioolkos** [comment]
@jadbaz thanks.
To my latest knowledge outgoing proxy protocol v2 is not supported in NGINX. See https://trac.nginx.org/nginx/ticket/1639, VerneMQ is even mentioned there.
You need v2 (binary version of proxy protocol) to pass on CN.
If my info is incorrect, happy to learn.

(I also have fixed some issues related to WS and PProtocol in main branch lately, but those are probably unrelated here).

**Comment by ioolkos** [comment]
Another option is to implement support for those X-forward headers from VerneMQ side. There's already a feature request for this:
https://github.com/vernemq/vernemq/issues/1754
Not working on this though.

**Comment by jadbaz** [comment]
Interesting
Supposing I'm not bound to nginx, could another webserver like HAProxy be able to do this?\
If not, I'm kinda puzzled how this feature in Vernemq exists but there's no example of how to actually use it

**Comment by ioolkos** [comment]
HAProxy has v2 proxy protocol support, yes.

**Comment by jadbaz** [comment]
Any working example code maybe?

**Comment by ioolkos** [comment]
For an HAProxy config? I can try throwing together an example, but you'll likely be faster than me.

Ultimately, I'd like to collect Proxy/Loadbalancer configs here: https://github.com/vernemq/vmq-proxy-configs (nothing there yet)

**Comment by jadbaz** [comment]
I've honestly never used HAProxy

**Comment by siepkes** [comment]
I recently tried the same thing with Envoy + PROXY Protocol V2 + VerneMQ Websocket and the CN as username. I also couldn't get it to work but I'll check it again and report back here.

**Comment by ioolkos** [comment]
@siepkes thanks, it's always interesting to know more. Supposing Envoy does support outgoing proxy protocol v2 (which I guess but haven't confirmed), let me know in case you think it's a WebSocket or Verne issue.

**Comment by ioolkos** [comment]
@siepkes I went ahead and tried to find out whether Envoy supports outgoing v2. I do not find any confirmation that it does. Maybe I'm just blind. Can you confirm you have actually been able to configure for outgoing v2?

**Comment by siepkes** [comment]
@ioolkos I believe like so:

```yaml

  - name: srv_vernemq_ws_proxyprotocol
    connect_timeout: 3s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    transport_socket:
      name: envoy.transport_sockets.upstream_proxy_protocol
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
        config:
          version: V2
        transport_socket:
          name: envoy.transport_sockets.raw_buffer
    load_assignment:
      cluster_name: srv_vernemq_ws_proxyprotocol
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 2444   
```
