### ISSUE TITLE
Broker does not authenticate with Redis/MySQL/MongoDB but with password file

### ISSUE THREAD

**Issue by NemesisFLX** [vernemq/vernemq#1813]
### Description

I want to run a VerneMQ Broker inside docker with a Redis/MySQL/MongoDB as the password database. I used Redis for the bug description because it was the easiest to reproduce, but also tried MySQL and MongoDB. 

**Expected Behavior**:
- Client A should be authenticated on subscribe
- Client B should be able to publish data after authentication
- Client A should receive data

**Actual Behavior**:
- Client A seems to be authenticated on subscribe
- Client B publishes data 
- Client A disconnects and reconnects
- Client A has no data received

This all works with a password file but not with a database.

**Steps to reproduce**:
1. `docker-compose up` on Broker
2.  `docker exec -it redis bash`
3.  `redis-cli`
4. `SET "[\"\",\"stefan\",\"stefan\"]" "{\"passhash\":\"$2a$12$PqE5JPkdtYstntK9cDfN4ODOWAvHoy4/79wc57g7sAAuMry1DK4qa\",\"subscribe_acl\":[{\"pattern\":\"#\"}], \"publish_acl\":[{\"pattern\":\"#\"}]}"`
5. `docker restart vmq` 

Client side: 

1. `mosquitto_sub --url mqtts://stefan:secretpassword@example.com:8883/Jupp/outgoing/G1 --id stefan --cafile letsencrypt.pem --debug --qos 2`
```
Client stefan sending CONNECT
Client stefan received CONNACK (0)
Client stefan sending SUBSCRIBE (Mid: 1, Topic: Jupp/outgoing/G1, QoS: 2, Options: 0x00)
Client stefan received SUBACK
Subscribed (mid: 1): 2
```

2. `mosquitto_pub --url mqtts://stefan:secretpassword@example.com:8883/Jupp/outgoing/G1 --id stefan -m "test" --debug --cafile letsencrypt.pem  --qos 2`
```
Client stefan sending CONNECT
Client stefan received CONNACK (0)
Client stefan sending PUBLISH (d0, q2, r0, m1, 'Jupp/outgoing/G1', ... (4 bytes))
Client stefan received PUBREC (Mid: 1)
Client stefan sending PUBREL (m1)
Client stefan received PUBCOMP (Mid: 1, RC:0)
Client stefan sending DISCONNECT
```

3. Subscriber seems to die without any message:
```
Client stefan sending CONNECT
Client stefan received CONNACK (0)
Client stefan sending SUBSCRIBE (Mid: 2, Topic: Jupp/outgoing/G1, QoS: 2, Options: 0x00)
Client stefan received SUBACK
Subscribed (mid: 2): 2
``` 

### Environment

- VerneMQ Version: 1.11.0-alpine
- OS: Docker Alpine

vernemq.conf: 

```conf
accept_eula = yes
allow_anonymous = off
listener.ssl.cafile = /etc/ssl/cacerts.pem
listener.ssl.certfile = /etc/ssl/cert.pem
listener.ssl.keyfile = /etc/ssl/key.pem
listener.ssl.default = 0.0.0.0:8883
plugins.vmq_diversity = on
plugins.vmq_passwd = off
plugins.vmq_acl = off
vmq_diversity.auth_redis.enabled = on
vmq_diversity.redis.host = redis
vmq_diversity.redis.port = 6379
allow_anonymous = off
```

docker-compose.yml:

```yml
version: "3.7"
services:
  vmq:
    image: vernemq/vernemq:1.11.0-alpine
    volumes:
      - ~/vernemq.conf:/etc/vernemq/vernemq.conf
      - ~/vmq.passwd:/etc/vernemq/vmq.passwd
      - ~/cert.pem:/etc/ssl/cert.pem
      - ~/key.pem:/etc/ssl/key.pem
      - ~/cacerts.pem:/etc/ssl/cacerts.pem
    ports:
      - "8883:8883"
  redis:
    image: redis
    ports:
      - "6379:6379"
```
