### ISSUE TITLE
Problem re-creating new pod with vernemq (standalone) on k8s with persistentVolumeClaim

### ISSUE THREAD

**Issue by kettenbach-it** [vernemq/vernemq#1837]
### Environment

- VerneMQ Version: 1.12 from latest docker
- OS: Docker Container vernemq/vernemq
- Erlang/OTP version (if building from source): --
- VerneMQ configuration (vernemq.conf) or the changes from the default: None
- Cluster size/standalone: Standalone

I'm running vernemq as a standalone server in GKE kubernetes.
The /data volume is mounted from a persistentVolumeClaim.
The pod is created as a deployment as follows:

```
      securityContext:
        fsGroup: 10000
      containers:
        - name: vernemq
          image: vernemq/vernemq
          volumeMounts:
            - name: mqtt-ktnbch-de-secret-cert
              mountPath: "/etc/secrets/cert"
              readOnly: true
            - name: mqtt-ktnbch-de-secret-key
              mountPath: "/etc/secrets/key"
              readOnly: true
            - name: vernemq-data
              mountPath: "/vernemq/data"
            - name: mysql-lua
              mountPath: "/vernemq/auth/"
          env:
            - name: DOCKER_VERNEMQ_ACCEPT_EULA
              value: 'yes'
            - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
              value: 'off'
            - name: DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD
              value: 'off'
            - name: DOCKER_VERNEMQ_PLUGINS__VMQ_ACL
              value: 'off'
            - name: DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY
              value: 'on'
            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__HOST
              value: 'mysql.xxxxxx.de'
            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__PORT
              value: '3306'
            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__DATABASE
              value: 'vernemq'
            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__USER
              value: 'vernemq'
            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__PASSWORD
              value: 'xxxxxxxxxxx'
            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQL__PASSWORD_HASH_METHOD
              value: 'sha1'

            - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__MYSQLACL__FILE
              value: '/vernemq/auth/mysql.lua'

            - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT
              value: '0.0.0.0:8883'
            - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__USE_IDENTITY_AS_USERNAME
              value: 'off'
            - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__REQUIRE_CERTIFICATE
              value: 'off'
            - name: DOCKER_VERNEMQ_LISTENER__SSL__CAFILE
              value: "/etc/secrets/cert/mqtt.xxxxxxxx.de.crt.pem"
            - name: DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE
              value: "/etc/secrets/cert/mqtt.xxxxxxxxx.de.crt.pem"
            - name: DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE
              value: "/etc/secrets/key/mqtt.xxxxxxxx.de.key.pem"
```

### Expected behaviour
After recreation of the pod, vernemq should start like it did the first time, where the files on /data where created 

### Actual behaviour
The pod does not start but fails with:

```
vernemq-78b7b77bd9-qtchs vernemq config is OK
vernemq-78b7b77bd9-qtchs vernemq -config /vernemq/data/generated.configs/app.2021.06.28.10.00.17.config -args_file /vernemq/bin/../etc/vm.args -vm_args /vernemq/bin/../etc/vm.args
vernemq-78b7b77bd9-qtchs vernemq Exec:  /vernemq/bin/../erts-11.2.1/bin/erlexec -boot /vernemq/bin/../releases/1.12.0/vernemq               -config /vernemq/data/generated.configs/app.2021.06.28.10.00.17.config -args_file /vernemq/bin/../etc/vm.args -vm_args /vernemq/bin/../etc/vm.args              -pa /vernemq/bin/../lib/erlio-patches -- console -noshell -noinput
vernemq-78b7b77bd9-qtchs vernemq Root: /vernemq/bin/..
vernemq-78b7b77bd9-qtchs vernemq 10:00:20.465 [info] alarm_handler: {set,{system_memory_high_watermark,[]}}
vernemq-78b7b77bd9-qtchs vernemq 10:00:21.243 [info] writing (updated) old actor <<66,174,247,114,200,105,228,64,70,128,9,22,72,167,205,111,149,146,215,53>> to disk
vernemq-78b7b77bd9-qtchs vernemq 10:00:21.266 [info] writing state {[{[{actor,<<66,174,247,114,200,105,228,64,70,128,9,22,72,167,205,111,149,146,215,53>>}],1}],{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[['VerneMQ@10.64.0.198',{[{actor,<<66,174,247,114,200,105,228,64,70,128,9,22,72,167,205,111,149,146,215,53>>}],1}]],[],[],[],[],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}} to disk <<75,2,131,80,0,0,0,249,120,1,203,96,206,97,96,96,96,204,96,130,82,41,12,172,137,201,37,249,69,185,64,81,17,167,117,223,139,78,100,62,113,112,107,224,20,243,88,126,54,127,234,164,235,166,89,137,140,89,25,156,41,12,44,41,153,201,37,137,140,137,2,64,200,145,24,144,104,144,33,144,133,6,50,24,17,98,96,227,65,4,83,10,131,112,88,106,81,94,170,111,160,131,161,129,158,153,137,158,129,158,161,165,5,105,14,128,89,132,112,8,3,177,14,129,105,5,0,34,16,78,15>>
vernemq-78b7b77bd9-qtchs vernemq 10:00:21.458 [info] Opening LevelDB SWC database at "./data/swc_meta/meta1"
vernemq-78b7b77bd9-qtchs vernemq Loaded NodeClock fromDisk #{{'VerneMQ@10.64.0.198',
vernemq-78b7b77bd9-qtchs vernemq                                 <<66,174,247,114,200,105,228,64,70,128,9,22,
vernemq-78b7b77bd9-qtchs vernemq                                   72,167,205,111,149,146,215,53>>} =>
vernemq-78b7b77bd9-qtchs vernemq                                 {189,0}}
vernemq-78b7b77bd9-qtchs vernemq 10:00:21.493 [error] Error in process <0.224.0> on node 'VerneMQ@10.64.0.33' with exit value:
vernemq-78b7b77bd9-qtchs vernemq {badarg,[{erlang,binary_to_term,[<<131,104,2,116,0,0,0,1,104,2,104,2,100,0,19,86,101,114,110,101,77,81,64,49,48,46,54,52,46,48,46,49,57,56,109,0,0,0,20,66,174,247,114,200,105,228,64,70,128,9,22,72,167,205,111,149,146,215,53,97,186,104,2,104,3,98,0,0,6,88,98,0,13,82,206,98,0,12,213,72,104,4,100,0,10,114,101,116,97,105,110,95,109,115,103,109,0,0,0,1,49,116,0,0,0,0,100,0,9,117,110,100,101,102,105,110,101,100,116,0,0,0,1,104,2,100,0,19,86,101,114,110,101,77,81,64,49,48,46,54,52,46,48,46,49,57,56,109,0,0,0,20,66,174,247,114,200,105,228,64,70,128,9,22,72,167,205,111,149,146,215,53,97,186>>,[safe]],[]},{vmq_swc_store,'-init_dotkeymap/1-fun-1-',4,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,763}]},{vmq_swc_db_leveldb,iterate,6,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,138}]},{vmq_swc_db_leveldb,'-handle_call/3-fun-1-',6,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,110}]}]}

```
Could it have something to do with the fact that the IP address of the pod has changed?
