### ISSUE TITLE
QOS1 message doesn't get delivered on re-subscription.

### ISSUE THREAD

**Issue by josh4500** [vernemq/vernemq#1937]
Message published with QOS1 (which are supposed to be delivered atLeastOnce to the subscriber) doesn't get delivered when the other client isn't online and came back online.

###Client Connection Configuration
- unique clientId
- clean_session = false
- topic subscription QOS1
- published Message with QOS1

### Client Environment
Flutter (mqtt_client) [https://github.com/shamblett/mqtt_client/]()
 
### Environment
VerneMQ Version: 1.12.3
OS:
Erlang/OTP version (if building from source):
VerneMQ configuration (vernemq.conf) or the changes from the default
Cluster size/standalone: 1

**Comment by ioolkos** [comment]
@josh4500 thanks, this is known to work, so there's unfortunately not much I can do to help you.
One thing: make sure that you don't have another broker running, capturing 1883 port, as an example.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by NikhilCodes** [comment]
To give additional info about our vernemq setup,

docker-compose.yml
```
version: "3"
services:
  vernemq:
    image: erlio/docker-vernemq
    container_name: vernemq
    restart: always
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'off'
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'

      # Disable these plugins to make all the webhooks work as expected
      DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS: 'on'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_PUBLISH__HOOK: 'on_publish'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_PUBLISH__ENDPOINT: 'http://ip:8000/a>
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REG__HOOK: 'auth_on_register'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REG__ENDPOINT: 'http://ip:8000/>
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_REG__HOOK: 'on_register'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_REG__ENDPOINT: 'http://ip:8000/api/v>
      DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES: 100000
      DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES: 100000
    ports:
      - 1883:1883
      - 8888:8888
    expose:
      - 1883
```

On using `vmq-admin listener show` 
```
+------+-------+----------+-----+----------+---------+
| type |status |    ip    |port |mountpoint|max_conns|
+------+-------+----------+-----+----------+---------+
| http |running|127.0.0.1 |8888 |          |  10000  |
| http |running|172.21.0.2|8888 |          |  10000  |
| vmq  |running|172.21.0.2|44053|          |  10000  |
|mqttws|running|172.21.0.2|8080 |          |  10000  |
| mqtt |running|172.21.0.2|1883 |          |  10000  |
+------+-------+----------+-----+----------+---------+
```

Any help would be appreciated!
