### ISSUE TITLE
 Docker default - can't authenticate client due to no_matching_hook_found

### ISSUE THREAD

**Issue by flinthamm** [vernemq/vernemq#1964]
### Environment

- VerneMQ Version: Both 1.12.3-alpin and 1.12.4-alpine
- OS: Linux Docker
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default - See below
- Cluster size/standalone: Standalone

```
version: '3'

services:

  vernemq:
    image: vernemq/vernemq:1.12.3-alpine
    container_name: vernemq
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off
      - DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT=on
      - DOCKER_VERNEMQ_USER_DEMO=passWORD
      - DOCKER_VERNEMQ_LOG.console.level=error

```

### Expected behaviour

It was expected that this basic docker setup using the example environment variables from the documentation would be sufficient for this container to work and accept authentication connections from existing MQTT clients. They already successfully connect to a simple Mosquitto docker install on the same server.

The Mosquitto container was removed in favour of spinning this one up as a test, however it immediately complains with the error "[error] can't authenticate client  ...  from 192.168.x.1:50966 due to no_matching_hook_found"?

Despite searched through the open/closed issues and the Forum there doesn't seem to be any help diagnosing what appears to be a configuration issue? There is mention of "no_matching_hook_found" for other authentication mechanisms (postgres, etc) but no answers that helped.

### Actual behaviour

The above docker compose file is all that has been used, although some other options (environment variables) have been tried to no avail and this is all that's mentioned on the official docker hub page.

I would be very grateful for any pointers or assistance as this looks like a great alternative to Mosquitto that it would be good to test.
