### ISSUE TITLE
Vernemq subscriber not receiving messages after 2 hours

### ISSUE THREAD

**Issue by vikash1508** [vernemq/vernemq#1969]
### Environment

- VerneMQ Version:1.10.0
- OS:Linux
- Erlang/OTP version (if building from source):Package
- Cluster size/standalone:1
- VerneMQ configuration (vernemq.conf) or the changes from the default:
I'm using Verne MQ from the Kubernetes cluster:
```
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: vernemq
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: vernemq
  serviceName: vernemq
  template: 
    metadata: 
      labels: 
        app: vernemq
    spec:
      serviceAccountName: vernemq
      containers:
      - name: vernemq
        image: erlio/docker-vernemq:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - /usr/sbin/vmq-admin cluster leave node=VerneMQ@${MY_POD_NAME}.vernemq.${DOCKER_VERNEMQ_KUBERNETES_NAMESPACE}.svc.cluster.local ; sleep 1 ; /usr/sbin/vmq-admin cluster leave node=VerneMQ@${MY_POD_NAME}.vernemq.${DOCKER_VERNEMQ_KUBERNETES_NAMESPACE}.svc.cluster.local -k
        ports:
        - containerPort: 1883
          name: mqtt
          hostPort: 1883
        - containerPort: 8883
        - containerPort: 4369
          name: epmd
        - containerPort: 44053
          name: vmq
        - containerPort: 8888
          name: health
        - containerPort: 9100
        - containerPort: 9101
        - containerPort: 9102
        - containerPort: 9103
        - containerPort: 9104
        - containerPort: 9105
        - containerPort: 9106
        - containerPort: 9107
        - containerPort: 9108
        - containerPort: 9109
        - containerPort: 8888
        resources:
          limits:
            cpu: "2"
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 1Gi
        env:
        - name: DOCKER_VERNEMQ_ACCEPT_EULA
          value: "yes"
        - name: MY_POD_NAME
          valueFrom:
           fieldRef:
             fieldPath: metadata.name
        - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
          value: "1"
        - name: DOCKER_VERNEMQ_KUBERNETES_APP_LABEL
          value: "vernemq"
        - name: DOCKER_VERNEMQ_KUBERNETES_NAMESPACE
          valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
        - name: DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MINIMUM
          value: "9100"
        - name: DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MAXIMUM
          value: "9109"
        - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
          value: "on"
        - name:  DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT
          value: "0.0.0.0:1883"
        - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__POOL_timeout
          value: "6000"
        - name: DOCKER_VERNEMQ_LISTENER__HTTP__DEFAULT
          value: "0.0.0.0:8888"
        - name: DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS
          value: "infinity"
        - name: DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS
          value: "10000"
        - name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
          value: "0"
        - name:  DOCKER_VERNEMQ_ALLOW_MULTIPLE_SESSIONS
          value: "on"
        - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
          value: "on"
        - name: ALLOW_PUBLISH_DURING_NETSPLIT
          value: "on"
        - name: ALLOW_SUBSCRIBE_DURING_NETSPLIT
          value: "on"
        - name: ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
          value: "on"
---
apiVersion: v1
kind: Service
metadata:
  name: vernemq
  labels:
    app: vernemq
spec:
  clusterIP: None
  selector:
    app: vernemq
  ports:
  - port: 4369
    name: empd
  - port: 44053
    name: vmq
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  type: LoadBalancer
  selector:
    app: vernemq
  ports:
  - port: 1883
    name: mqtt
    targetPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: health
  labels:
    app: health
spec:
  type: LoadBalancer
  selector:
    app: vernemq
  ports:
  - port: 8888
    name: health
    targetPort: 8888
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vernemq
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-reader
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["endpoints", "deployments", "replicasets", "pods"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-reader
subjects:
- kind: ServiceAccount
  name: vernemq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vernemq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vernemq
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status:
  observedGeneration: 1
  lastScaleTime: 5
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
```

### Expected behaviour

- Subscribers for the topic must receive messages whenever the publisher sends messages to that topic

### Actual behaviour

- After 2 hours the subscribers for the topic are not receiving any messages. When we restart the VerneMQ pod we are getting the messages for the topic but again after 2hours, we are not getting any messages in the subscriber.
During this time I'm not able to any issues in console logs and there is only one node in the cluster and its status is also healthy.

Trace logs from publish:

> <8973.15409.28> MQTT RECV: CID: "Publisher-client-1" CONNECT(c: Publisher-client-1, v: 4, u: undefined, p: undefined, cs: 1, ka: 60)
<8973.15409.28> MQTT SEND: CID: "Publisher-client-1" CONNACK(sp: 0, rc: 0)
<8973.15409.28> MQTT RECV: CID: "Publisher-client-1" SUBSCRIBE(m1) with topics:
    q:2, t: "test/topic1"
<8973.15409.28> Calling auth_on_subscribe(undefined,{[],
                                                     <<"Publisher-client-1">>}) with topics:
    q:2, t: "test/topic1"
<8973.15409.28> Hook returned "ok"
<8973.15409.28> MQTT RECV: CID: "Publisher-client-1" PUBLISH(d0, q2, r0, m2, "test/topic1") with payload:
    "test-message-1"
<8973.15409.28> Calling auth_on_publish(undefined,{[],
                                                   <<"Publisher-client-1">>},2,test/topic1,false) with payload:
    "test-message-1"
<8973.15409.28> Hook returned "ok"
<8973.15409.28> MQTT RECV: CID: "Publisher-client-1" PUBLISH(d0, q2, r0, m3, "test/topic1") with payload:
    "test-message-1"
<8973.15409.28> Calling auth_on_publish(undefined,{[],
                                                   <<"Publisher-client-1">>},2,test/topic1,false) with payload:
    "test-message-1"
<8973.15409.28> Hook returned "ok"
<8973.15409.28> MQTT RECV: CID: "Publisher-client-1" PUBLISH(d0, q2, r0, m4, "test/topic1") with payload:
    "test-message-1"
<8973.15409.28> Calling auth_on_publish(undefined,{[],
                                                   <<"Publisher-client-1">>},2,test/topic1,false) with payload:
    "test-message-1"
<8973.15409.28> Hook returned "ok"
<8973.15409.28> MQTT RECV: CID: "Publisher-client-1" PINGREQ()
<8973.15409.28> MQTT SEND: CID: "Publisher-client-1" PINGRESP()
<8973.15409.28> MQTT RECV: CID: "Publisher-client-1" PUBLISH(d0, q2, r0, m5, "test/topic1") with payload:
    "test-message-1"
<8973.15409.28> Calling auth_on_publish(undefined,{[],
                                                   <<"Publisher-client-1">>},2,test/topic1,false) with payload:
    "test-message-1"
<8973.15409.28> Hook returned "ok"

Trace log from subscriber client:

> <8973.10681.47> Trace session for Subscriber-client-1 stopped
New session with PID <8973.12030.47> found for client "Subscriber-client-1"
<8973.12030.47> MQTT RECV: CID: "Subscriber-client-1" CONNECT(c: Subscriber-client-1, v: 4, u: undefined, p: undefined, cs: 1, ka: 60)
<8973.12030.47> MQTT SEND: CID: "Subscriber-client-1" CONNACK(sp: 0, rc: 0)
<8973.12030.47> MQTT RECV: CID: "Subscriber-client-1" SUBSCRIBE(m49) with topics:
    q:2, t: "test/topic1"
<8973.12030.47> Calling auth_on_subscribe(undefined,{[],
                                                     <<"Subscriber-client-1">>}) with topics:
    q:2, t: "test/topic1"
<8973.12030.47> Hook returned "ok"
