### ISSUE TITLE
Unable to start (?) with this error: exec /usr/sbin/start_vernemq: exec format error

### ISSUE THREAD

**Issue by TheNighthawk99** [vernemq/vernemq#2029]
Hello, just installed VerneMQ through the following docker-compose file along with Ecowitt2Mqtt container:

```
version: "3"
services:

#### ECOWITT-2-MQTT
  ecowitt2mqtt:
    container_name: WZ_ecowitt2mqtt
    image: "bachya/ecowitt2mqtt:latest"
    environment:
      ECOWITT2MQTT_VERBOSE: "true"
      ECOWITT2MQTT_ENDPOINT: /data/report
      ECOWITT2MQTT_PORT: 8080
      ECOWITT2MQTT_MQTT_BROKER: WZ_vernemq
      ECOWITT2MQTT_MQTT_PORT: 1883
      ECOWITT2MQTT_MQTT_TOPIC: GW1100/device01
      ECOWITT2MQTT_USERNAME: jimbo
      ECOWITT2MQTT_PASSWORD: limbo
    ports:
      - "8080:8080/tcp"
    restart: always

      
#### VERNEMQ
  vernemq:
    container_name: WZ_vernemq
    hostname: vernemq
    image: vernemq/vernemq
    restart: unless-stopped
    user: root
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_USER_ECOWITT: "limbo"
    ports:
      - "1883:1883/tcp"
      - "8888:8888"
```

The container log says this:

`exec /usr/sbin/start_vernemq: exec format error`
