### ISSUE TITLE
auth_on_register webhook is not called when anonymous clients are allowed

### ISSUE THREAD

**Issue by hahahannes** [vernemq/vernemq#2049]
### Environment
- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behaviour
I use this docker compose to run VerneMQ and want to use the `auth_on_register` webhook to block incoming clients and also want to use client TLS certificate for authentication. To only use certficiates and no username/passoword. I set `allow_anonymous=on`.  For simplicity reason, I removed the certificates configuration as the behaviour can be seen without it.

```
version: '3'

services:
  vernmq:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS: "on"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__HOOK1__HOOK: auth_on_register
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__HOOK1__ENDPOINT: http://foo:8080
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
    ports:
      - 1883:1883
```
I expect the webhook to be called.

### Actual behaviour
It is not called. As described in other issues, this is inteded when `allow_anonymous=on`. But I wonder how I can setup my usecase where I need `auth_on_register` to block clients. The `on_register` webhook is only outgoing and does not impact the client connection if I understand correctly.

Thank you!
