### ISSUE TITLE
[Bug]: Node failure causes cluster restart

### ISSUE THREAD

**Issue by win5923** [vernemq/vernemq#2299]
### Environment

- VerneMQ Version: vernemq:2.0.0-alpine
- OS: Ubuntu Linux
- Erlang/OTP version (if building from source): erlang-dev (25.3.2.2-r0)
- Cluster size/standalone: 3 node

### Current Behavior

Hi, I am currently using a custom Dockerfile to build an image from scratch. Everything works fine up until the cluster creation step, but I encounter an issue when testing connection numbers using the default configuration.

After some time, a node suddenly experiences a `parse error: Invalid numeric literal at line 1, column 4` issue, causing the entire cluster to restart. Could you help me understand what might be causing this problem?

### Expected behaviour

One node going down shouldn't cause the entire cluster to go down.

### Configuration, logs, error output, etc.

After vernemq-1 encounters the `parse error: Invalid numeric literal at line 1, column 4`, vernemq-0 and vernemq-2 are unable to connect to vernemq-1, which subsequently causes the vernemq cluster to restart.

vernemq-0 logs:
![image](https://github.com/vernemq/vernemq/assets/56353753/ced3640c-2f6d-4c24-9677-f03d2e6564c5)

vernemq-1 logs (crash-pod):
![image](https://github.com/vernemq/vernemq/assets/56353753/b56834ff-2b1d-4778-a07f-6c0cdec5968f)

vernemq-2 logs:
![image](https://github.com/vernemq/vernemq/assets/56353753/5538fa7f-1964-4e11-a1da-36108413109d)

```yaml
additionalEnv:
  - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
    value: "on"
  # - name: DOCKER_VERNEMQ_ACCEPT_EULA
  #   value: "yes"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "on"
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct
