### ISSUE TITLE
[Bug]: Error on cluster startup 

### ISSUE THREAD

**Issue by pellepelster** [vernemq/vernemq#2310]
### Environment

- VerneMQ Version: 2.0.0
- OS: official VerneMQ docker image
- Cluster size/standalone: 2 node cluster

### Current Behavior

During evaluation of the VerneMQ 2.0 docker image we observed some weird issues during cluster startup. We are running VerneMQ in K8S using the VerneMQ helm chart. 

Assuming a clean cluster with no previous deployment, the cluster starts fine, but when redeploying again during pod rotation by the StatefulSet the first pod that gets terminated and started again fails for properly start with this message:

```
Runtime terminating during boot ({{badkey,{'VerneMQ@172.26.0.3',<<13,199,20,12,50,139,154,26,231,215,232,27,187,181,74,218,20,95,50,182>>}},[{erlang,map_get,[{'VerneMQ@172.26.0.3',<<13,199,20,12,50,139,154,26,231,215,232,27,187,181,74,218,20,95,50,182>>},#{}],[{error_info,#{module=>erl_erts_errors}}]},{vmq_swc_plugin,'-summary/1-lc$^1/1-1-',3,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_plugin.erl"},{line,220}]},{vmq_swc_plugin,history,1,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_plugin.erl"},{line,230}]},{vmq_swc_peer_service,attempt_join,1,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_peer_service.erl"},{line,57}]},{vmq_server_cli,'-vmq_cluster_join_cmd/0-fun-1-',3,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_server_cli.erl"},{line,516}]},{clique_command,run,1,[{file,"/opt/vernemq/_build/default/lib/clique/src/clique_command.erl"},{line,87}]},{vmq_server_cli,command,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_server_cli.erl"},{line,45}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,746}]}]})
```

We were able to reproduce this locally with the following `docker-compose.yml`

```
version: '3.5'

services:

  vernemq1:
    image: docker-hub.testo.dev/vernemq/vernemq:2.0.0
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_COMPOSE=on
    volumes:
      - vernemq1:/vernemq/data
    networks:
      - vernemq

  vernemq2:
    image: docker-hub.testo.dev/vernemq/vernemq:2.0.0
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_DISCOVERY_NODE=vernemq1
      - DOCKER_VERNEMQ_COMPOSE=on
    volumes:
    - vernemq2:/vernemq/data
    networks:
      - vernemq

networks:
  vernemq:
    name: vernemq

volumes:
  vernemq1:
  vernemq2:
```

The following steps result in the described error:

1. Create both VerneMQ nodes

```
docker-compose up -d
```

cluster formation seems ok, we can see the following log line

```
vernemq2_1  | 2024-06-06T08:25:37.920390+00:00 [info] <0.711.0> vmq_cluster_node:handle_message/2:220: successfully connected to cluster node 'VerneMQ@172.26.0.2'
```

and `vmq-admin cluster show` shows

```
+--------------------+---------+
| Node               | Running |
+--------------------+---------+
| VerneMQ@172.26.0.2 | true    |
+--------------------+---------+
| VerneMQ@172.26.0.3 | true    |
+--------------------+---------+
```

2. stop all nodes `docker-compose stop`
3. start all nodes again `docker-compose start`

looking at the logs `docker-compose logs -f` the second node consistently fails with

```
vernemq2_1  | 2024-06-06T08:28:21.087071+00:00 [error] <0.9.0>: Error in process <0.9.0> on node 'VerneMQ@172.26.0.2' with exit value:, {{badkey,{'VerneMQ@172.26.0.2',<<191,60,5,252,193,92,106,78,25,98,133,181,82,244,69,161,221,52,49,64>>}},[{erlang,map_get,[{'VerneMQ@172.26.0.2',<<191,60,5,252,193,92,106,78,25,98,133,181,82,244,69,161,221,52,49,64>>},#{}],[{error_info,#{module => erl_erts_errors}}]},{vmq_swc_plugin,'-summary/1-lc$^1/1-1-',3,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_plugin.erl"},{line,220}]},{vmq_swc_plugin,history,1,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_plugin.erl"},{line,230}]},{vmq_swc_peer_service,attempt_join,1,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_peer_service.erl"},{line,57}]},{vmq_server_cli,'-vmq_cluster_join_cmd/0-fun-1-',3,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_server_cli.erl"},{line,516}]},{clique_command,run,1,[{file,"/opt/vernemq/_build/default/lib/clique/src/clique_command.erl"},{line,87}]},{vmq_server_cli,command,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_server_cli.erl"},{line,45}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,746}]}]}
vernemq2_1  | 
vernemq1_1  | 2024-06-06T08:28:21.088686+00:00 [warning] <0.421.0> vmq_cluster_mon:handle_info/2:127: cluster node 'VerneMQ@172.26.0.2' DOWN
vernemq2_1  | Crash dump is being written to: /erl_crash.dump...[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
vernemq2_1  | [os_mon] memory supervisor port (memsup): Erlang has closed
```

### Expected behaviour

see current behaviour

### Configuration, logs, error output, etc.

```markdown
see current behaviour
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct
