### ISSUE TITLE
disconnected due to multiple sessions not allowed

### ISSUE THREAD

**Issue by goldyfruit** [vernemq/vernemq#2346]
### Environment

- VerneMQ Version: `2.0.1`
- OS: Debian Bookworm
- Erlang/OTP version (if building from source):
- Cluster size/standalone: `standalone`

### Current Behavior

I'm running a Python application leveraging FastAPI-MQTT for a while now but today I decided it was time to upgrade my old VerneMQ 1.13 version cluster to 2.0.1. So I rebuild the [Docker image](https://hub.docker.com/layers/smartgic/vernemq/2.0.1/images/sha256-0b444ed6181bd6e606f2313f727a49d92e4d83d768e297076f16e60c5ad92315?context=explore), create a new cluster, connect it to my Redis instance _(`authn`/`authz`)_ and all if fine from a cluster perspective.

Since the upgrade, the application keeps connecting/disconnecting and when I check in the VerneMQ log I see an error about multiple sessions. I checked in the documentation and it seems that the multiple sessions support has been fully removed in VerneMQ 2.x which is fine.

The thing is that I don't know why the application tries to get multiple sessions, my Python code is pretty simple.

```python
import json
from fastapi_mqtt.fastmqtt import FastMQTT
from fastapi_mqtt.config import MQTTConfig
from app.common import database as db
from app.common import constants
from app.config import get_settings

settings = get_settings()

mqtt_config = MQTTConfig(
    host=settings.mqtt_host,
    port=settings.mqtt_port,
    username=settings.mqtt_user,
    password=settings.mqtt_password,
    keepalive=settings.mqtt_keepalive,
    ssl=settings.mqtt_ssl,
)

mqtt = FastMQTT(client_id=settings.mqtt_client, clean_session=True, config=mqtt_config)


@mqtt.on_connect()
def connect(client, flags, rc, properties):
    for subcription in constants.MQTT_SUBSCRIPTIONS:
        mqtt.client.subscribe(subcription)
    print("Connected: ", client, flags, rc, properties)


@mqtt.on_disconnect()
def disconnect(client, packet, exc=None):
    print("Disconnected")


@mqtt.on_subscribe()
def subscribe(client, mid, qos, properties):
    print("subscribed", client, mid, qos, properties)


@mqtt.on_message()
async def message(client, topic, payload, qos, properties):
    # print("Received message: ", topic, payload.decode(), qos, properties)
    topic = topic.split("/")[-1]
    data = json.loads(payload.decode())
    info = db.get_device(data["serial_number"])
    if info is not None and info["active"]:
        key = constants.DEVICE_DOCUMENT_TYPE + ":" + str(info["id"])
        db.update_document(key, data["status"], ".status", False)
```

Here is the data store within Redis about the `authn` and  `authz`:

```json
{
    "passhash": "$2a$10$VDPcc4T9H6SI8bY7uhFAley.kuw/z9G2p15PZjWZrSanNpHlY2R6S",
    "subscribe_acl": [
        {
            "pattern": "response/status/+"
        },
        {
            "pattern": "response/configuration/+"
        }
    ],
    "publish_acl": [
        {
            "pattern": "request/configuration/+"
        },
        {
            "pattern": "request/status/+"
        }
    ]
}
```

Any reason how to prevent the multiple sessions happening?

### Expected behaviour

Keeps the client connected.

### Configuration, logs, error output, etc.

VerneMQ log:
```
2024-08-29T21:08:45.024133+00:00 [debug] <0.1225.0> vmq_queue:online/3:282: client {[],<<"backend">>} disconnected due to multiple sessions not allowed
2024-08-29T21:08:45.024870+00:00 [debug] <0.1222.0> vmq_mqtt5_fsm:connected/2:811: stop due to disconnect
2024-08-29T21:08:45.024834+00:00 [debug] <0.1225.0> vmq_queue:state_change/3:1380: transition from online --> wait_for_offline because of add_session
2024-08-29T21:08:45.025769+00:00 [debug] <0.1222.0> vmq_ranch:teardown/2:185: session normally stopped
```

Application log:
```
Connected:  <gmqtt.client.Client object at 0x7f6597a133e0> 0 0 {}
subscribed <gmqtt.client.Client object at 0x7f6597a133e0> 1 (135,) {}
subscribed <gmqtt.client.Client object at 0x7f6597a133e0> 2 (135,) {}
Disconnected
Disconnected
Connected:  <gmqtt.client.Client object at 0x7f7dd33deed0> 1 0 {}
subscribed <gmqtt.client.Client object at 0x7f7dd33deed0> 1 (135,) {}
subscribed <gmqtt.client.Client object at 0x7f7dd33deed0> 2 (135,) {}
Disconnected
Connected:  <gmqtt.client.Client object at 0x7fe28cb83530> 1 0 {}
Disconnected
subscribed <gmqtt.client.Client object at 0x7fe28cb83530> 1 (135,) {}
subscribed <gmqtt.client.Client object at 0x7fe28cb83530> 2 (135,) {}
Disconnected
Disconnected
Connected:  <gmqtt.client.Client object at 0x7fca59e17770> 1 0 {}
subscribed <gmqtt.client.Client object at 0x7fca59e17770> 1 (135,) {}
subscribed <gmqtt.client.Client object at 0x7fca59e17770> 2 (135,) {}
Disconnected
Connected:  <gmqtt.client.Client object at 0x7f6597a133e0> 1 0 {}
Disconnected
subscribed <gmqtt.client.Client object at 0x7f6597a133e0> 3 (135,) {}
subscribed <gmqtt.client.Client object at 0x7f6597a133e0> 4 (135,) {}
Disconnected
Disconnected
Connected:  <gmqtt.client.Client object at 0x7f7dd33deed0> 1 0 {}
subscribed <gmqtt.client.Client object at 0x7f7dd33deed0> 3 (135,) {}
subscribed <gmqtt.client.Client object at 0x7f7dd33deed0> 4 (135,) {}
Disconnected
Connected:  <gmqtt.client.Client object at 0x7fe28cb83530> 1 0 {}
Disconnected
subscribed <gmqtt.client.Client object at 0x7fe28cb83530> 3 (135,) {}
subscribed <gmqtt.client.Client object at 0x7fe28cb83530> 4 (135,) {}
```

Configuration used:
```yaml
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: 'on'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED: 'on'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PORT: 6379
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST: 10.17.2.164
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__USER: default
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PASSWORD: xxxx
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__DATABASE: 0
      DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT__ALLOWED_PROTOCOL_VERSIONS: 3,4,5
      DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS: 3,4,5
      DOCKER_VERNEMQ_LISTENER__TCP__PROXY_PROTOCOL: 'on'
      DOCKER_VERNEMQ_LISTENER__TCP__PROXY_PROTOCOL_USE_CN_AS_USERNAME: 'on'
      DOCKER_VERNEMQ_LISTENER__WS__DEFAULT: 0.0.0.0:9002
      DOCKER_VERNEMQ_LISTENER__WS__PROXY_PROTOCOL: 'on'
      DOCKER_VERNEMQ_LISTENER__WS__PROXY_PROTOCOL_USE_CN_AS_USERNAME: 'on'
      DOCKER_VERNEMQ_LISTENER__WS__ALLOWED_PROTOCOL_VERSIONS: 3,4,5
      DOCKER_VERNEMQ_LOG__CONSOLE: 'both'
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: debug
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct
