### ISSUE TITLE
bridge to NanoMQ causes a loop of messages

### ISSUE THREAD

**Issue by alessiopollero** [vernemq/vernemq#2406]
### Environment

- VerneMQ Version: 2.0.1
- OS: Docker image vernemq/vernemq:latest
- Cluster size/standalone: one node 

My docker compose file is similar to the following: 

```
networks:
  iot_internal_network:
    driver: bridge

services:
  vernemq:
    image: vernemq/vernemq:latest
    container_name: vernemq_broker
    networks:
      - iot_internal_network
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_PLUGINS.vmq_bridge=on
      - DOCKER_VERNEMQ_VMQ_BRIDGE.tcp.nanomqdatanet=172.90.90.1:1883
      - DOCKER_VERNEMQ_VMQ_BRIDGE.tcp.nanomqdatanet.cleansession=on
      - DOCKER_VERNEMQ_VMQ_BRIDGE.tcp.nanomqdatanet.client_id=test_bridge
      - DOCKER_VERNEMQ_VMQ_BRIDGE.tcp.nanomqdatanet.username=mqtt-user
      - DOCKER_VERNEMQ_VMQ_BRIDGE.tcp.nanomqdatanet.password=test
      - DOCKER_VERNEMQ_VMQ_BRIDGE.tcp.nanomqdatanet.topic.1=TTT/SLT9/* both 1
      - DOCKER_VERNEMQ_VMQ_BRIDGE.tcp.nanomqdatanet.restart_timeout=10
      - DOCKER_VERNEMQ_VMQ_BRIDGE.tcp.nanomqdatanet.try_private=off
    ports:
      - "1883:1883"



```

Whenever I send a message to to the topic `TTT/SLT9/CMD/SOMECOMMAND`
it looks like I run in a loop and messages and responses are entering in a loop basically generating so many messages that are going to overwhelm the NanoMQ instance on the other side of the bridge.
Is there a way to prevent this issue either built in or with some forwarding rules on the bridge configuration ? 

I don't know if this can be considered a bug or not, but probably as the VerneMQ should prevent this loop of messages in the first place I believe. 

Thanks in advance for any help.

### Current Behavior

Messages are looping on the topics between the two bridged MQTT brokers and causing resources exhaustion 

### Expected behaviour

There should be some loop prevention mechanism that avoids this issue 

### Configuration, logs, error output, etc.

```markdown

```

### Code of Conduct

- [x] I agree to follow the VerneMQ's Code of Conduct
