### ISSUE TITLE
Run bcrypt on multiple cores [was: Authentication with Redis fails "due to error"]

### ISSUE THREAD

**Issue by trehn** [vernemq/vernemq#579]
### Environment

- VerneMQ Version: 1.2.3
- OS: Docker

### Configuration

```
  mqtt:
    environment:
      - DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS=96000
      - DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS=100
      - DOCKER_VERNEMQ_MAX_CLIENT_ID_SIZE=32
      - DOCKER_VERNEMQ_MAX_MESSAGE_SIZE=524288
      - DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION=1h
      - DOCKER_VERNEMQ_PLUGINS__VMQ_ACL=off
      - DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=on
      - DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD=off
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED=on
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST=redis
    image: erlio/docker-vernemq:1.2.3
    ports:
      - "8081:8080"
      - "8888:8888"
    restart: always
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
```

### Problem

I have a single client that – after working fine for weeks – can no longer connect. Every attempt results in a CONNACK 5 (unauthorized). I triple-checked the password and manually validated the bcrypt hash in redis.

The only log message I get is:

```
[warning] <0.3218.0>@vmq_mqtt_fsm:check_user:544 can't authenticate client {[],<<"XXX">>} due to error
```

Peeking at the code, the word "error" is formatted into that log line, in place of a more informative description of the problem. It originates somewhere deeper down the stack.

Of course, this only occurs in production. All other clients work just fine and I can't reproduce the problem elsewhere. The only thing that is special about this client is that it may have had a higher volumes of messages in general and misbehaved in the past (excessive reconnects, simultaneous/duplicate connections).

With my very limited understanding of Erlang and VerneMQ, I was unable to figure out where that "error" originated. Without going deeper into why this single client acts up, maybe we can first figure out what the actual error is and where it originates? Better error messages are always a good thing :)

P.S.: This may or may not be related, but I have seen this error sporadically for other clients too:

```
[error] <0.725.0>@vmq_diversity_script:call_function:64 can't call into Lua sandbox for function auth_on_register due to {timeout,{gen_server,call,[<0.601.0>,{call_function,auth_on_register,[{addr,<<"172.18.0.1">>},{port,58256},{mountpoint,<<>>},{client_id,<<"XXX">>},{username,<<"XXX">>},{password,<<"XXX">>},{clean_session,true}]}]}}
```

That doesn't appear to be a persistent problem however.
