### ISSUE TITLE
docker-compose mongodb without auth

### ISSUE THREAD

**Issue by molotsnk** [vernemq/vernemq#991]
Hi, in first i must say that vernemq great! I using verne + mongodb with docker-compose. If  using connection mongodb with auth it working fine , but if use open mongodb without --auth flag it no working. Please help!   Heare config:
```
    version: '3.6'
    services:
      senslab-mongodb:
        image: mongo:4.0.4-xenial
        container_name: senslab-mongodb
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27000:27017
        command:
            - '--smallfiles'
            - '--bind_ip_all'
#        environment:
#              - MONGO_INITDB_ROOT_USERNAME=user
#              - MONGO_INITDB_ROOT_PASSWORD=pass
#              - MONGO_INITDB_DATABASE=senslab
        networks:
              - senslab

      mqtt:
        image: erlio/docker-vernemq:1.6.1
        container_name: senslab-vernemqt
        ports:
           - 1883:1883
           - 8080:8080
           - 8000:8000
        depends_on:
           - senslab-mongodb
        environment:
           - DOCKER_VERNEMQ.plugins.vmq_passwd = off
           - DOCKER_VERNEMQ.plugins.vmq_diversity = on
           - DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.port = 27000
           - DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.host = 172.21.0.1
           - DOCKER_VERNEMQ_VMQ_DIVERSITY.auth_mongodb.enabled = on
#           - DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.login = null
#           - DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.password = null
           - DOCKER_VERNEMQ_VMQ_DIVERSITY.mongodb.database = senslab
           - DOCKER_VERNEMQ_LISTENER.ws.1=0.0.0.0:8000
        networks:
           - senslab
      nats-senslab:
        image: nats:1.3.0-linux
        ports:
            - 8222:8222
            - 4222:4222
        hostname: nats-server
        networks:
            - senslab

    volumes:
        mongodb:
        mongodb_config:

    networks:
      senslab:
        driver: bridge
 
```
Vernomq log: 
```
18:52:28.397 [info] enable auth script for mongodb "/usr/share/vernemq/lua/auth/mongodb.lua"
18:52:28.518 [info] Application vmq_server started on node 'VerneMQ@172.21.0.4'
18:52:28.518 [info] Application dht_ring started on node 'VerneMQ@172.21.0.4'
18:52:39.603 [warning] can't authenticate client {[],<<"x0rium">>} due to
                              invalid_credentials
```
Mongodb:
db.getCollection('vmq_acl_auth').find({})

```
{
    "_id" : ObjectId("5c06c6c7a1a47d6d257a2e4f"),
    "publish_acl" : [ 
        {
            "pattern" : "#"
        }
    ],
    "subscribe_acl" : [ 
        {
            "pattern" : "#"
        }
    ],
    "client_id" : "x0rium",
    "username" : "x0rium",
    "passhash" : "$2a$10$8ULky7TtdlRFFLQmk95dCOqMCL5VCUnFX2MUaULS/LxiyrxUiTwHq",
    "__v" : 0
}
```
